name: vtracker
description: An Android app for tracking and managing rides (Vehicle Tracking System)

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  location: ^4.2.0
  google_maps_flutter: ^2.1.10
  place_picker: ^0.9.20-nullsafety
  open_street_map_search_and_pick:
    git:
      url: https://github.com/MoutazDebbaneh/open_street_map_search_and_pick
  multi_select_flutter:
    git:
      url: https://github.com/MoutazDebbaneh/multi_select_flutter
  flutter_secure_storage: ^6.0.0
  intl: ^0.17.0
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.8

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon.png
    - assets/images/car_icon.png
    - assets/images/bus_icon.png
    - assets/images/location_a.png
    - assets/images/location_b.png

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
